{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end -}}
