export enum OtpStoreAction {
    GET_CODE = 'GET_CODE',
    GET_INFO = 'GET_INFO',
    REPORT_PHONE_NUMBER = 'REPORT_PHONE_NUMBER',
    RESET_STATE = 'RESET_STATE',
    RETRY_GET_CODE = 'RETRY_GET_CODE',
    VERIFY_CODE = 'VERIFY_CODE',
}
