export enum OtpStoreMutation {
    RESET_STATE = 'RESET_STATE',
    SET_ERROR = 'SET_ERROR',
    SET_INFO = 'SET_INFO',
    SET_IS_RETRYING = 'SET_IS_RETRYING',
    SET_REPORTED_PHONE_NUMBER = 'SET_REPORTED_PHONE_NUMBER',
    SET_STATE = 'SET_STATE',
}
