apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  APACHE_RUN_USER: {{ .Values.apache.run.user }}
  APACHE_RUN_GROUP: {{ .Values.apache.run.group }}
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}