export enum SessionStoreAction {
    GET_LOGIN_OPTIONS = 'GET_LOGIN_OPTIONS',
    LOGIN_BY_CODE = 'LOGIN_BY_CODE',
    LOGOUT = 'LOGOUT',
    SET_LANGUAGE = 'SET_LANGUAGE',
    GET_NEW_PAIRING_CODE = 'GET_NEW_PAIRING_CODE',
    CLEAR_DIGID_RESPONSE = 'CLEAR_DIGID_RESPONSE',
}
