export enum SessionStoreMutation {
    LOGOUT = 'LOGOUT',
    SET_NAME = 'SET_NAME',
    SET_LANGUAGE = 'SET_LANGUAGE',
    SET_LOGIN_OPTIONS = 'SET_LOGIN_OPTIONS',
    CLEAR_DIGID_RESPONSE = 'CLEAR_DIGID_RESPONSE',
    SET_PAIRING_CODE_RESPONSE = 'SET_PAIRING_CODE_RESPONSE',
}
